### ISSUE TITLE
zm static function is used in roki-fd

### ISSUE THREAD

**Issue by categoryik** [mi-lib/zm#2]
I have got bellow error because _zQPSolveASM is static function although roki-fd is using _zQPSolveASM.
```bash
agcc -ansi -Wall -O3 `roki-config -L` `roki-gl-config -L` `roki-fd-config -L` `roki-config -I` `roki-gl-config -I` `roki-fd-config -I` -funroll-loops -g -o main main.c `roki-config -l` `roki-gl-config -l` `roki-fd-config -l`
/usr/bin/ld: /usr/lib/libroki-fd.so: undefined reference to `_zQPSolveASM'
collect2: error: ld returned 1 exit status
make: *** [makefile:12: main] Error 1
```

**Comment by zhidao** [comment]
I threw an issue in mi-lib/roki-fd repository as the above.

**Comment by zhidao** [comment]
Let me close this issue because _zQPSolveASM() has been successfully reimplemented in RoKi-FD https://github.com/mi-lib/roki-fd/commit/b960edebd903d026addb65b01265585a868b8259
